services:
  - type: web
    name: antonine-study-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && node src/migrate.js
    startCommand: node src/index.js
    envVars:
      - key: DB_HOST
        value: "dpg-d85k9d0js32c73alq1q0-a"
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: "antonine_study"
      - key: DB_USER
        value: "antonine"
      - key: DB_PASSWORD
        value: "jzvsoQJgVKU26WkmtUXI6qOyK7i4Jjfe"
      - key: SERVER_PORT
        value: "8080"
